---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.27.1
    app.quarkus.io/commit-id: 60092ae4be2e6e98609a3d7509e280f3961b9a4f
    app.quarkus.io/vcs-uri: https://github.com/orpiske/wanaku.git
    app.quarkus.io/build-timestamp: 2026-01-21 - 13:53:12 +0000
  labels:
    app.kubernetes.io/name: wanaku-operator
    app.kubernetes.io/version: 0.1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: wanaku-operator
